channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=24.0
- pip:
  - mlflow<3,>=2.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - graphviz==0.20.1
  - lightgbm==3.3.2
  - matplotlib==3.6.0
  - numpy==1.23.5
  - packaging==23.1
  - pandas==1.5.3
  - pathlib==1.0.1
  - psutil==5.9.5
  - scikit-learn==1.1.3
  - scipy==1.10.1
  - typing-extensions==4.9.0
name: mlflow-env
