channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=24.0
- pip:
  - mlflow<3,>=2.3
  - catboost==1.2.2
  - cloudpickle==2.2.1
  - ipywidgets==8.0.6
  - mypy-extensions==1.0.0
  - numpy==1.23.5
  - pandas==1.5.3
  - pathlib==1.0.1
  - scikit-learn==1.1.3
  - scipy==1.10.1
  - typing-extensions==4.9.0
  - xgboost==1.5.2
name: mlflow-env
